be_challenge/apps/ui/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView, ImportEmployeesCSVView, ImportShiftsCSVView


import_csv_urls = [
    path('employees/', ImportEmployeesCSVView.as_view(), name='employees'),
    path('shifts/', ImportShiftsCSVView.as_view(), name='shifts'),
]


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('import_csv/', include((import_csv_urls, 'roster'), namespace='import_csv')),
]

be_challenge/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import RedirectView

from be_challenge.apps.roster.urls import urlpatterns as roster_urlpatterns
from be_challenge.apps.ui.urls import urlpatterns as ui_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include(roster_urlpatterns)),
    path('', include(ui_urlpatterns)),
    path('', RedirectView.as_view(pattern_name='home', permanent=False)),
]

be_challenge/apps/ui/models.py
from django.db import models

# Create your models here.

be_challenge/apps/ui/forms.py
from django import forms


class UploadCSVFileForm(forms.Form):
    file = forms.FileField(widget=forms.FileInput(attrs={'accept': ".csv"}))

be_challenge/apps/ui/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView

from .forms import UploadCSVFileForm
from be_challenge.apps.roster.utils import import_employees_csv, import_shifts_csv
from be_challenge.apps.roster.models import EmployeesCSVFile, ShiftsCSVFile


class HomeView(TemplateView):
    template_name = 'index.html'


class ImportEmployeesCSVView(FormView):
    form_class = UploadCSVFileForm
    template_name = 'import_employees_csv.html'

    def form_valid(self, form):
        file = form.cleaned_data.get('file')
        csv_file = EmployeesCSVFile(file=file)
        csv_file.save()

        result = import_employees_csv(csv_file.file.file.name)

        # Display import result message to user
        if result['status'] == 'success':
            messages.success(
                self.request,
                result['message'],
                extra_tags='alert alert-success safe'
            )
        else:
            messages.error(
                self.request,
                result['message'],
                extra_tags='alert alert-danger safe'
            )
        return HttpResponseRedirect(reverse_lazy('home'))

    def form_invalid(self, form):
        # Display error message
        messages.error(
            self.request,
            "Error: Please review below and re-submit.",
            extra_tags='alert alert-danger'
        )
        return super().form_invalid(form)


class ImportShiftsCSVView(FormView):
    form_class = UploadCSVFileForm
    template_name = 'import_shifts_csv.html'

    def form_valid(self, form):
        file = form.cleaned_data.get('file')
        csv_file = ShiftsCSVFile(file=file)
        csv_file.save()

        result = import_shifts_csv(csv_file.file.file.name)

        # Display import result message to user
        if result['status'] == 'success':
            messages.success(
                self.request,
                result['message'],
                extra_tags='alert alert-success safe'
            )
        else:
            messages.error(
                self.request,
                result['message'],
                extra_tags='alert alert-danger safe'
            )
        return HttpResponseRedirect(reverse_lazy('home'))

    def form_invalid(self, form):
        # Display error message
        messages.error(
            self.request,
            "Error: Please review below and re-submit.",
            extra_tags='alert alert-danger'
        )
        return super().form_invalid(form)

be_challenge/apps/ui/templates/base.html
<!DOCTYPE html>
<html>
	{% block head %}
		<head>
			<meta charset="utf-8">
	    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	    
	    	{% block title %}
				<title>Biarri Challenge</title>
			{% endblock %}

			{% block css %}
				<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
			{% endblock %}
		</head>
	{% endblock %}

	<body>
		<div class="container">
			{% block content %}
			{% endblock %}
		</div>
	</body>
</html>

be_challenge/apps/ui/templates/import_csv.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">
		<div class="col-12">
			{% block page_title %}<h4>Import CSV File</h4>{% endblock %}
			<form action="{% block form_action %}{% endblock %}" method="post" enctype="multipart/form-data">
			    {% csrf_token %}
			    {{ form.as_p }}
			    <a class="btn btn-secondary" href="{% url 'home' %}">Back</a>
			    <button type="submit" class="btn btn-success">Import</button>
			</form>
		</div>
	</div>
{% endblock %}

be_challenge/apps/ui/templates/import_employees_csv.html
{% extends 'import_csv.html' %}

{% block page_title %}<h4>Import Employees CSV File</h4>{% endblock %}

{% block form_action %}{% url 'import_csv:employees' %}{% endblock %}

be_challenge/apps/ui/templates/import_shifts_csv.html
{% extends 'import_csv.html' %}

{% block page_title %}<h4>Import Shifts CSV File</h4>{% endblock %}

{% block form_action %}{% url 'import_csv:shifts' %}{% endblock %}

be_challenge/apps/ui/templates/index.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">
		<div class="col-12">
			<h4>Home</h4>
			{% for message in messages %}
				<div class="{{ message.tags }}" role="alert">
					{% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
				</div>
            {% endfor %}
			<a class="btn btn-primary" href="{% url 'import_csv:employees' %}">Import Employees CSV</a>
			<a class="btn btn-primary" href="{% url 'import_csv:shifts' %}">Import Shifts CSV</a>
		</div>
	</div>
{% endblock %}